"""add missing tables

Revision ID: c151da14ba0c
Revises: 
Create Date: 2026-04-14 18:02:13.999616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c151da14ba0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_winner', sa.Integer(), nullable=True),
    sa.Column('score_loser', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['teams.id'], name=op.f('fk_matches_loser_id_teams')),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], name=op.f('fk_matches_winner_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_table('team_challenge',
    sa.Column('challenger_id', sa.Integer(), nullable=False),
    sa.Column('challenged_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenged_id'], ['teams.id'], name=op.f('fk_team_challenge_challenged_id_teams')),
    sa.ForeignKeyConstraint(['challenger_id'], ['teams.id'], name=op.f('fk_team_challenge_challenger_id_teams')),
    sa.PrimaryKeyConstraint('challenger_id', 'challenged_id', name=op.f('pk_team_challenge'))
    )
    op.create_table('team_match',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_team_match_match_id_matches')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_match_team_id_teams')),
    sa.PrimaryKeyConstraint('team_id', 'match_id', name=op.f('pk_team_match'))
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('product',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('email_ousd'))
        batch_op.drop_index(batch_op.f('email_personal'))
        batch_op.drop_index(batch_op.f('google_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email_ousd'), ['email_ousd'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_email_personal'), ['email_personal'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_google_id'), ['google_id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_team_id_teams'), 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_team_id_teams'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_users_google_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email_personal'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email_ousd'), type_='unique')
        batch_op.create_index(batch_op.f('google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('email_personal'), ['email_personal'], unique=True)
        batch_op.create_index(batch_op.f('email_ousd'), ['email_ousd'], unique=True)
        batch_op.drop_column('team_id')

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('product',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=True)

    op.drop_table('team_match')
    op.drop_table('team_challenge')
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
